name: CratesPlus
description: ${project.description}
main: plus.crates.CratesPlus
version: ${project.version}
api-version: 1.13
author: Connor Linfoot
softdepend: [HolographicDisplays,IndividualHolograms]
commands:
  crate:
    description: Main CratesPlus command
    aliases: [cratesplus,crates]
permissions:
  cratesplus.admin:
    default: op
  cratesplus.updates:
    default: op
